### ISSUE TITLE
在线展示排版方面的问题

### ISSUE THREAD

**Issue by wj23027** [kaiyuanshe/2023-China-Open-Source-Report#4]
现已将数据篇、问卷篇、商业化篇（校对前的版本）合入 GitHub，测试[在线展示](https://kaiyuanshe.github.io/2023-China-Open-Source-Repor)的效果，目前发现几个排版上的小问题：

#### 1. 右侧的文章目录无法折叠，并且无法跟随文章内容滑动，而有些章节目录比较长，不太方便阅读

![屏幕截图 2024-01-29 165351](https://github.com/kaiyuanshe/2023-China-Open-Source-Report/assets/62098023/f3c47317-36cc-4f52-ae17-3b51a116d2f7)

#### 2. 表格排版效果不好（没有居中、部分表格展示效果不佳）

![image](https://github.com/kaiyuanshe/2023-China-Open-Source-Report/assets/62098023/82329771-1948-45db-b7d4-89c9a340d1ef)

#### 3. 部分图表使用html标签排版失效了（最好需要统一图表排版方式）
例如此处左右布局排版失效
![image](https://github.com/kaiyuanshe/2023-China-Open-Source-Report/assets/62098023/3df365db-8663-45ff-ab50-3f7d478d6daf)

**Comment by stevending1st** [comment]
> 现已将数据篇、问卷篇、商业化篇（校对前的版本）合入 GitHub，测试[在线展示](https://kaiyuanshe.github.io/2023-China-Open-Source-Repor)的效果，目前发现几个排版上的小问题：
> 
> #### 1. 右侧的文章目录无法折叠，并且无法跟随文章内容滑动，而有些章节目录比较长，不太方便阅读
做不了

> #### 2. 表格排版效果不好（没有居中、部分表格展示效果不佳）
做不了

> #### 3. 部分图表使用html标签排版失效了（最好需要统一图表排版方式）

可以写 `vue` 组件
